# EDGAR Financial RAG System
 
## Overview
 
This notebook provides a natural language interface to analyze SEC filings (10-K and 10-Q) for five major tech companies, a regulated utility, and an AI cloud provider:
- **AMZN** - Amazon
- **GOOGL** - Alphabet/Google
- **META** - Meta/Facebook
- **MSFT** - Microsoft
- **ORCL** - Oracle
- **D** - Dominion Energy
- **CRWV** - Coreweave
 
**Data Coverage:** January 2020 - Present (CRWV from IPO, March 2025)
 
## Architecture
 
The system combines two complementary data sources:
 
### 1. Structured Financial Data (XBRL)
- Financial facts extracted from balance sheets, income statements, and cash flow statements
- **Standardized XBRL concepts** - consistent metric names across all companies
- **SQL queryable** - precise numerical queries with date ranges and filtering
- **Use for:** Revenue, expenses, equity, assets, specific financial metrics
 
### 2. Narrative Content (Vector RAG)
- Text chunks from risk factors, MD&A, business descriptions
- **Vector embeddings** via Voyage AI for semantic search
- **PostgreSQL pgvector** - efficient similarity search
- **Use for:** Risks, strategies, qualitative discussions, business context
 
### 3. Intelligent Query Router
- **Claude classifies** each query as quantitative, qualitative, or both
- **Automatically retrieves** from appropriate data sources
- **Synthesizes answers** combining numbers with narrative context

## Quick Start

The simplest way to use this system is the `ask()` function:
 
```python
ask("How much did Amazon spend on infrastructure in 2025?")
ask("What risks does Microsoft mention about AI and power?")
ask("Compare data center spending across the hyperscalers")
ask("What does Coreweave say about its GPU cloud business?")
```
 
## Example Use Cases
 
**Quantitative Analysis:**
- Track infrastructure spending trends across companies
- Compare equity growth rates
- Analyze CapEx trajectories
 
**Qualitative Analysis:**
- Identify energy and power-related risks
- Understand data center expansion strategies
- Compare AI investment narratives

**Hybrid Analysis:**
- "How much is Microsoft spending on AI infrastructure and what do they say about power requirements?"
- "Compare AWS vs Azure capital investments and their growth strategies"
- "How is Dominion Energy's generation mix changing alongside hyperscaler capex growth?"
- "What does Coreweave's balance sheet look like and how do they describe their GPU cloud strategy?"
 
## Data Freshness
 
This system contains filings through early May 2026. To update:
1. Run `python edgar_parser.py` to fetch new filings
2. Run `python generate_embeddings.py` to embed new chunks
3. Restart this notebook kernel

---

# EDGAR Financial RAG System
 
This notebook provides a natural language interface to query:
- **Structured financial data** (XBRL facts via SQL)
- **Narrative content** (risk factors, MD&A via vector search)
- **Synthesized answers** (Claude combines both)

In [1]:
import os
import json
import re
from datetime import date
import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv
import voyageai
from anthropic import Anthropic

load_dotenv()

# Runtime config (keep in sync with generate_embeddings.py)
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "voyage-3-lite")
TODAY_STR = date.today().isoformat()

# Initialize clients
engine = create_engine(
    f"postgresql://{os.getenv('POSTGRES_USER')}:{os.getenv('POSTGRES_PASSWORD')}@"
    f"{os.getenv('POSTGRES_HOST')}:{os.getenv('POSTGRES_PORT')}/{os.getenv('POSTGRES_DB')}"
)
voyage_client = voyageai.Client(api_key=os.getenv("VOYAGE_API_KEY"))
anthropic_client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

print("✓ Clients initialized")
print(f"✓ Embedding model: {EMBEDDING_MODEL}")
print(f"✓ Today: {TODAY_STR}")

/home/daniel/projects/edgar_rag/power/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✓ Clients initialized
✓ Embedding model: voyage-3-lite
✓ Today: 2026-06-17

## Helper Functions

In [2]:
def analyze_query(question):
    """
    Use Claude to analyze the query and extract structured search parameters.
    Replaces classify_query_type, extract_company_ticker, and extract_keywords.
    """
    prompt = f"""Analyze this financial question and extract structured search parameters.

Question: {question}

Available companies and tickers:
- AMZN (Amazon)
- GOOGL (Alphabet/Google)
- META (Meta/Facebook)
- MSFT (Microsoft)
- ORCL (Oracle)
- D (Dominion Energy)
- CRWV (Coreweave)

Available financial statement types: balance_sheet, income_statement, cashflow

Example XBRL labels in our database (use these to generate precise sql_keywords):
- "Technology and infrastructure", "Cost of sales", "Total operating expenses"
- "Property and equipment, net", "Capital expenditures", "Purchases of property and equipment"
- "Total assets", "Total current assets", "Cash and cash equivalents"
- "Total stockholders equity", "Retained earnings", "Additional paid-in capital"
- "Revenue", "Net income", "Operating income", "Net sales"
- "Long-term debt", "Total liabilities", "Accounts payable"
- "Depreciation and amortization", "Stock-based compensation"
- "Research and development", "General and administrative"

Respond with ONLY valid JSON (no markdown, no explanation):
{{
  "query_type": "quantitative | qualitative | both",
  "tickers": ["TICKER1", "TICKER2"],
  "sql_keywords": ["keyword phrase 1", "keyword phrase 2"],
  "date_range": {{"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}} or null,
  "narrative_search_query": "optimized search query for vector similarity" or ""
}}

Rules:
- query_type: "quantitative" for numbers/metrics, "qualitative" for risks/strategies/narratives, "both" for combined
- tickers: list ALL companies mentioned. Empty list [] if no specific company mentioned (searches all)
- sql_keywords: 2-5 precise phrases that would match XBRL labels or concepts via SQL ILIKE. Think about what the financial line items would actually be called in SEC filings. Do NOT include apostrophes in keywords.
- date_range: extract if the question mentions a time period (e.g., "last 2 years" means start 2024-01-01, end 2026-12-31). null if no time constraint
- narrative_search_query: a concise, semantically rich query for vector search. Empty string "" if purely quantitative
- Today's date is {TODAY_STR} for calculating relative date ranges"""

    response = anthropic_client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}]
    )

    raw = response.content[0].text.strip()

    # Parse JSON with fallback
    try:
        analysis = json.loads(raw)
    except json.JSONDecodeError:
        # Try to extract JSON from markdown code blocks or surrounding text
        match = re.search(r'\{.*\}', raw, re.DOTALL)
        if match:
            try:
                analysis = json.loads(match.group())
            except json.JSONDecodeError:
                analysis = None
        else:
            analysis = None

        if analysis is None:
            # Fallback to safe defaults
            analysis = {
                "query_type": "both",
                "tickers": [],
                "sql_keywords": ["revenue", "income"],
                "date_range": None,
                "narrative_search_query": question
            }

    # Validate tickers
    valid_tickers = {'AMZN', 'GOOGL', 'META', 'MSFT', 'ORCL', 'D', 'CRWV'}
    analysis['tickers'] = [t for t in analysis.get('tickers', []) if t in valid_tickers]

    return analysis


# Apostrophe characters to strip from both DB labels and search keywords.
# DB labels use Unicode right single quote (U+2019), but keywords from Claude
# typically omit apostrophes entirely. Stripping both sides ensures matching.
_APOSTROPHES = "‘’'`´"
_APOSTROPHE_RE = re.compile(f"[{_APOSTROPHES}]")


def search_financial_facts(keywords, tickers=None, date_range=None, limit=20):
    """
    Search structured financial facts using keyword matching.
    Supports multiple keywords, multiple tickers, and date range filtering.
    Ensures balanced per-ticker results when multiple tickers are requested.
    """
    if not keywords:
        return pd.DataFrame()

    keyword_conditions = []
    base_params = {}
    for i, kw in enumerate(keywords[:8]):
        kw_clean = _APOSTROPHE_RE.sub("", kw)
        param_name = f'keyword{i}'
        keyword_conditions.append(
            f"(REPLACE(REPLACE(label, E'\\u2019', ''), '''', '') ILIKE :{param_name}"
            f" OR REPLACE(REPLACE(concept, E'\\u2019', ''), '''', '') ILIKE :{param_name})"
        )
        base_params[param_name] = f'%{kw_clean}%'

    keyword_clause = " OR ".join(keyword_conditions)

    base_query = f"""
        SELECT 
            ticker,
            period_date,
            statement_type,
            label,
            value,
            unit,
            filing_type,
            filing_date
        FROM financial_facts_clean
        WHERE ({keyword_clause})
    """

    if date_range:
        if date_range.get('start'):
            base_query += " AND period_date >= :date_start"
            base_params['date_start'] = date_range['start']
        if date_range.get('end'):
            base_query += " AND period_date <= :date_end"
            base_params['date_end'] = date_range['end']

    # Single-ticker or all-ticker behavior
    if not tickers or len(tickers) <= 1:
        query = base_query
        params = dict(base_params)

        if tickers:
            params['ticker0'] = tickers[0].upper()
            query += " AND ticker = :ticker0"

        effective_limit = limit
        if date_range:
            effective_limit *= 3

        query += " ORDER BY ticker, label, period_date DESC LIMIT :limit"
        params['limit'] = effective_limit

        with engine.connect() as conn:
            return pd.read_sql(text(query), conn, params=params)

    # Multi-ticker behavior: query each ticker separately for balanced coverage
    per_ticker_limit = max(5, limit)
    if date_range:
        per_ticker_limit *= 3

    frames = []
    with engine.connect() as conn:
        for ticker in tickers:
            ticker_query = base_query + " AND ticker = :ticker ORDER BY label, period_date DESC LIMIT :limit"
            params = dict(base_params)
            params['ticker'] = ticker.upper()
            params['limit'] = per_ticker_limit

            df = pd.read_sql(text(ticker_query), conn, params=params)
            if not df.empty:
                frames.append(df)

    if not frames:
        return pd.DataFrame()

    out = pd.concat(frames, ignore_index=True)
    out = out.sort_values(['ticker', 'label', 'period_date'], ascending=[True, True, False])
    return out.reset_index(drop=True)


def search_narrative(query_text, tickers=None, limit=5, similarity_threshold=0.35):
    """
    Search narrative chunks using vector similarity.
    Supports multiple tickers and filters out low-similarity results.
    """
    if not query_text:
        return pd.DataFrame()

    # Generate query embedding
    query_embedding = voyage_client.embed(
        texts=[query_text],
        model=EMBEDDING_MODEL,
        input_type="query"
    ).embeddings[0]

    embedding_str = "[" + ",".join(map(str, query_embedding)) + "]"

    # Inner query fetches extra candidates to allow threshold filtering
    inner_limit = limit * 3

    inner_query = """
        SELECT 
            ticker,
            filing_type,
            filing_date,
            section,
            chunk_text,
            1 - (embedding <=> CAST(:query_embedding AS vector)) as similarity
        FROM document_chunks
        WHERE embedding IS NOT NULL
    """

    params = {'query_embedding': embedding_str}

    # Multi-ticker support
    if tickers:
        ticker_placeholders = []
        for i, t in enumerate(tickers):
            param_name = f'ticker{i}'
            ticker_placeholders.append(f":{param_name}")
            params[param_name] = t.upper()
        inner_query += f" AND ticker IN ({', '.join(ticker_placeholders)})"

    inner_query += """
        ORDER BY embedding <=> CAST(:query_embedding AS vector)
        LIMIT :inner_limit
    """
    params['inner_limit'] = inner_limit

    # Wrap with similarity threshold filter
    sql_query = f"""
        SELECT * FROM ({inner_query}) sub
        WHERE similarity >= :threshold
        LIMIT :outer_limit
    """
    params['threshold'] = similarity_threshold
    params['outer_limit'] = limit

    with engine.connect() as conn:
        # ivfflat default probes=1 scans only 1 of 100 lists; for
        # underrepresented tickers (e.g. D) that single probed list can
        # contain zero matching rows, causing the ticker filter to wipe
        # out all candidates. probes=10 (sqrt(lists)) is pgvector's
        # recommended recall setting.
        conn.execute(text("SET ivfflat.probes = 10"))
        return pd.read_sql(text(sql_query), conn, params=params)

## Main Query Function

In [3]:
def query_edgar(question, max_financial_results=20, max_narrative_results=5, synthesize=True):
    """
    Main query interface - routes to appropriate data sources and optionally synthesizes answer.
    
    Args:
        question: Natural language question
        max_financial_results: Max financial facts to retrieve
        max_narrative_results: Max narrative chunks to retrieve
        synthesize: Whether to use Claude to synthesize final answer
    
    Returns:
        dict with 'financial_data', 'narrative_data', and optionally 'answer'
    """
    print(f"\n{'='*60}")
    print(f"QUERY: {question}")
    print('='*60)
    
    # Analyze query with Claude
    analysis = analyze_query(question)
    
    query_type = analysis['query_type']
    tickers = analysis['tickers']
    sql_keywords = analysis['sql_keywords']
    date_range = analysis.get('date_range')
    narrative_search_query = analysis.get('narrative_search_query', '')
    
    print(f"\nQuery type: {query_type}")
    print(f"Tickers: {tickers if tickers else 'all'}")
    print(f"SQL keywords: {sql_keywords}")
    if date_range:
        print(f"Date range: {date_range['start']} to {date_range['end']}")
    if narrative_search_query:
        print(f"Narrative query: {narrative_search_query}")
    
    results = {}
    
    # Fetch financial data if needed
    if query_type in ['quantitative', 'both']:
        print("\n🔢 Searching financial facts...")
        financial_df = search_financial_facts(sql_keywords, tickers, date_range, max_financial_results)
        results['financial_data'] = financial_df
        print(f"   Found {len(financial_df)} financial facts")
    
    # Fetch narrative data if needed
    if query_type in ['qualitative', 'both']:
        print("\n📄 Searching narrative chunks...")
        narrative_df = search_narrative(narrative_search_query, tickers, max_narrative_results)
        results['narrative_data'] = narrative_df
        print(f"   Found {len(narrative_df)} relevant chunks")
    
    # Synthesize answer with Claude
    if synthesize:
        print("\n🤖 Synthesizing answer with Claude...")
        results['answer'] = synthesize_answer(question, results)
    
    return results


def synthesize_answer(question, data):
    """Use Claude to synthesize a comprehensive answer from retrieved data."""
    
    # Build context from retrieved data
    context_parts = []
    
    if 'financial_data' in data and not data['financial_data'].empty:
        df = data['financial_data']
        context_parts.append("# Financial Data\n\n")
        # Group by ticker and show key metrics (up to 20 rows per ticker for trend coverage)
        for ticker in df['ticker'].unique():
            ticker_data = df[df['ticker'] == ticker].head(20)
            context_parts.append(f"## {ticker}\n")
            for _, row in ticker_data.iterrows():
                context_parts.append(
                    f"- {row['label']}: ${row['value']:.0f}M ({row['period_date']}, {row['filing_type']})\n"
                )
            context_parts.append("\n")
    
    if 'narrative_data' in data and not data['narrative_data'].empty:
        df = data['narrative_data']
        context_parts.append("\n# Narrative Context\n\n")
        for idx, row in df.head(5).iterrows():
            context_parts.append(
                f"## {row['ticker']} - {row['section'][:60]}... "
                f"({row['filing_type']} {row['filing_date']}, similarity: {row['similarity']:.3f})\n\n"
                f"{row['chunk_text'][:800]}...\n\n"
            )
    
    context = "".join(context_parts)
    
    if not context.strip():
        return "No relevant data found to answer this question."
    
    # Generate answer
    response = anthropic_client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[{
            "role": "user",
            "content": f"""You are a financial analyst assistant. Answer the following question using ONLY the provided data from SEC filings.

Question: {question}

Retrieved Data:
{context}

Instructions:
- Provide a clear, concise answer
- Cite specific numbers and dates from the data
- If comparing companies, create a clear comparison
- If the data doesn't fully answer the question, say so
- Do not make up information not in the data"""
        }]
    )
    
    return response.content[0].text

## Example Queries

In [4]:
# Example 1: Quantitative query
result = query_edgar(
    "How much did Amazon spend on technology and infrastructure in 2025?",
    synthesize=True
)

if 'financial_data' in result:
    print("\n" + "="*60)
    print("FINANCIAL DATA")
    print("="*60)
    display(result['financial_data'])

if 'answer' in result:
    print("\n" + "="*60)
    print("SYNTHESIZED ANSWER")
    print("="*60)
    print(result['answer'])

============================================================
QUERY: How much did Amazon spend on technology and infrastructure in 2025?
============================================================

Query type: quantitative
Tickers: ['AMZN']
SQL keywords: ['Technology and infrastructure', 'Technology infrastructure', 'Capital expenditures', 'Purchases of property and equipment', 'Total operating expenses']
Date range: 2025-01-01 to 2025-12-31

🔢 Searching financial facts...
   Found 12 financial facts

🤖 Synthesizing answer with Claude...

============================================================
FINANCIAL DATA
============================================================

,ticker,period_date,statement_type,label,value,unit,filing_type,filing_date
0,AMZN,2025-12-31,cashflow,Purchases of property and equipment,131819.0,millions,10-K,2026-02-06
1,AMZN,2025-09-30,cashflow,Purchases of property and equipment,92297.0,millions,10-Q,2025-10-31
2,AMZN,2025-06-30,cashflow,Purchases of property and equipment,57202.0,millions,10-Q,2025-08-01
3,AMZN,2025-03-31,cashflow,Purchases of property and equipment,25019.0,millions,10-Q,2026-04-30
4,AMZN,2025-12-31,income_statement,Technology and infrastructure,108521.0,millions,10-K,2026-02-06
5,AMZN,2025-09-30,income_statement,Technology and infrastructure,79122.0,millions,10-Q,2025-10-31
6,AMZN,2025-06-30,income_statement,Technology and infrastructure,50160.0,millions,10-Q,2025-08-01
7,AMZN,2025-03-31,income_statement,Technology and infrastructure,22994.0,millions,10-Q,2026-04-30
8,AMZN,2025-12-31,income_statement,Total operating expenses,636949.0,millions,10-K,2026-02-06
9,AMZN,2025-09-30,income_statement,Total operating expenses,448540.0,millions,10-Q,2025-10-31
10,AMZN,2025-06-30,income_statement,Total operating expenses,285793.0,millions,10-Q,2025-08-01
11,AMZN,2025-03-31,income_statement,Total operating expenses,137262.0,millions,10-Q,2026-04-30

============================================================
SYNTHESIZED ANSWER
============================================================
## Amazon's Technology and Infrastructure Spending in 2025

Based on the **2025 annual 10-K filing (year ended December 31, 2025)**, Amazon spent:

### **$108,521 million (~$108.5 billion)** on Technology and Infrastructure

---

### Context & Additional Detail:

| Period | Technology & Infrastructure | Source |
|--------|----------------------------|--------|
| Q1 2025 (ending Mar 31) | $22,994M | 10-Q |
| Q2 2025 (ending Jun 30) | $50,160M | 10-Q (YTD) |
| Q3 2025 (ending Sep 30) | $79,122M | 10-Q (YTD) |
| **Full Year 2025 (ending Dec 31)** | **$108,521M** | **10-K** |

> **Note:** The quarterly figures above appear to be **year-to-date (cumulative)** values, which is consistent with the full-year figure of $108.5 billion reported in the annual 10-K.

This $108.5 billion in technology and infrastructure spending represented approximately **17%** of Amazon's total operating expenses of $636,949 million for the full year 2025. Additionally, Amazon made **$131.8 billion in capital expenditures** (property and equipment purchases) during the same period, reflecting its massive ongoing investment in physical and digital infrastructure.

In [5]:
# Example 2: Qualitative query
result = query_edgar(
    "What does Amazon mention related to data center power and energy?",
    synthesize=True
)

if 'narrative_data' in result:
    print("\n" + "="*60)
    print("NARRATIVE DATA")
    print("="*60)
    for idx, row in result['narrative_data'].head(3).iterrows():
        print(f"\n{idx+1}. {row['ticker']} {row['filing_type']} ({row['filing_date']})")
        print(f"   Section: {row['section'][:60]}...")
        print(f"   Similarity: {row['similarity']:.3f}")
        print(f"   {row['chunk_text'][:400]}...\n")

if 'answer' in result:
    print("\n" + "="*60)
    print("SYNTHESIZED ANSWER")
    print("="*60)
    print(result['answer'])

============================================================
QUERY: What does Amazon mention related to data center power and energy?
============================================================

Query type: qualitative
Tickers: ['AMZN']
SQL keywords: ['Technology and infrastructure', 'Capital expenditures', 'Property and equipment, net', 'Purchases of property and equipment']
Narrative query: Amazon data center power energy consumption electricity infrastructure capacity

📄 Searching narrative chunks...
   Found 5 relevant chunks

🤖 Synthesizing answer with Claude...

============================================================
NARRATIVE DATA
============================================================

1. AMZN 10-Q (2025-05-02)
   Section: Note 8 — SEGMENT INFORMATION...
   Similarity: 0.450
   AWS

The AWS segment consists of amounts earned from global sales of compute, storage, database, and other services for start-ups, enterprises, government agencies, and academic institutions.

Information on reportable segments and reconciliation to consolidated net income is as follows (in millions):

<div align='center'>19</div>

Table of Contents

Net sales by groups of similar products and ser...


2. AMZN 10-Q (2026-04-30)
   Section: Note 8 — SEGMENT INFORMATION...
   Similarity: 0.435
   AWS

The AWS segment consists of amounts earned from global sales of compute, storage, database, and other services for start-ups, enterprises, government agencies, and academic institutions.

Information on reportable segments and reconciliation to consolidated net income is as follows (in millions):

March 31,

<div align='center'>22</div>

Table of Contents

Net sales by groups of similar produ...


3. AMZN 10-K (2025-02-07)
   Section: Operating Risks...
   Similarity: 0.435
   We Face Risks Related to Successfully Optimizing and Operating Our Fulfillment Network and Data Centers

Failures to adequately predict customer demand and consumer spending patterns or otherwise optimize and operate our fulfillment network and data centers successfully from time to time result in excess or insufficient fulfillment or data center capacity, service interruptions, increased costs, a...


============================================================
SYNTHESIZED ANSWER
============================================================
## Amazon's Mentions of Data Center Power and Energy

Based on the provided SEC filing data, Amazon's disclosures on data center power and energy are **limited in the retrieved excerpts**, but here is what is mentioned:

### Key Risk Disclosures

Across multiple filings (10-K 2024-02-02, 10-K 2025-02-07, and 10-Q 2026-04-30), Amazon consistently identifies the following risk under **"We Face Risks Related to Successfully Optimizing and Operating Our Fulfillment Network and Data Centers"**:

- **Capacity risks**: Failures to predict demand can result in **excess or insufficient data center capacity**
- **Operational complexity**: As Amazon adds data center capability, networks become "increasingly complex and operating them becomes more challenging"
- **Financial impact**: These risks can lead to **service interruptions, increased costs, and impairment charges**

### Limitations of the Data

The retrieved excerpts **do not contain specific details** about:
- Power consumption levels or energy usage figures
- Renewable energy commitments or sustainability targets
- Power Purchase Agreements (PPAs)
- Specific energy infrastructure investments

The data primarily frames data center operations as a **business/operational risk** rather than providing detailed energy or power metrics.

> To get a more complete picture of Amazon's energy and power strategy, additional sections of their SEC filings (such as sustainability disclosures or capital expenditure discussions) would need to be reviewed.

In [6]:
# Example 3: Comparative query (both quantitative and qualitative)
result = query_edgar(
    "Compare data center infrastructure spending across Amazon, Microsoft, and Google",
    max_financial_results=30,
    synthesize=True
)

if 'financial_data' in result:
    print("\n" + "="*60)
    print("FINANCIAL DATA")
    print("="*60)
    display(result['financial_data'])

if 'answer' in result:
    print("\n" + "="*60)
    print("SYNTHESIZED ANSWER")
    print("="*60)
    print(result['answer'])

============================================================
QUERY: Compare data center infrastructure spending across Amazon, Microsoft, and Google
============================================================

Query type: both
Tickers: ['AMZN', 'MSFT', 'GOOGL']
SQL keywords: ['Capital expenditures', 'Purchases of property and equipment', 'Property and equipment, net', 'Technology and infrastructure', 'Depreciation and amortization']
Narrative query: data center infrastructure capital spending investment strategy cloud computing facilities

🔢 Searching financial facts...
   Found 87 financial facts

📄 Searching narrative chunks...
   Found 5 relevant chunks

🤖 Synthesizing answer with Claude...

============================================================
FINANCIAL DATA
============================================================

,ticker,period_date,statement_type,label,value,unit,filing_type,filing_date
0,AMZN,2026-03-31,cashflow,Depreciation and amortization of property and ...,18945.0,millions,10-Q,2026-04-30
1,AMZN,2025-12-31,cashflow,Depreciation and amortization of property and ...,65756.0,millions,10-K,2026-02-06
2,AMZN,2025-09-30,cashflow,Depreciation and amortization of property and ...,46285.0,millions,10-Q,2025-10-31
3,AMZN,2025-06-30,cashflow,Depreciation and amortization of property and ...,29489.0,millions,10-Q,2025-08-01
4,AMZN,2025-03-31,cashflow,Depreciation and amortization of property and ...,14262.0,millions,10-Q,2026-04-30
...,...,...,...,...,...,...,...,...
82,MSFT,2024-12-31,balance_sheet,"Property and equipment, net of accumulated dep...",166902.0,millions,10-Q,2025-01-29
83,MSFT,2025-03-31,balance_sheet,"Property and equipment, net of accumulated dep...",183939.0,millions,10-Q,2025-04-30
84,MSFT,2025-06-30,balance_sheet,"Property and equipment, net of accumulated dep...",204966.0,millions,10-K,2025-07-30
85,MSFT,2024-06-30,balance_sheet,"Property and equipment, net of accumulated dep...",135591.0,millions,10-K,2025-07-30
86,MSFT,2025-09-30,balance_sheet,"Property and equipment, net of accumulated dep...",230861.0,millions,10-Q,2025-10-29

============================================================
SYNTHESIZED ANSWER
============================================================
# Data Center Infrastructure Spending Comparison: Amazon, Microsoft & Google

## Important Methodology Note

The retrieved data contains **different metrics** for each company, making a direct apples-to-apples comparison difficult. Here's what's available:

- **Amazon (AMZN):** Depreciation & Amortization figures (cumulative YTD cash flow statement items)
- **Google (GOOGL):** Property & Equipment, Net (balance sheet)
- **Microsoft (MSFT):** Property & Equipment, Net (balance sheet)

> ⚠️ **No direct capex spending figures** are provided in the retrieved data. The analysis below uses available proxies.

---

## 1. Property & Equipment, Net (Balance Sheet Comparison)

This reflects the **accumulated stock of infrastructure assets** (Google & Microsoft only):

| Date | Google (GOOGL) | Microsoft (MSFT) |
|------|---------------|-----------------|
| **Q1 2026** (Mar 31, 2026) | **$281,020M** | **$283,228M** |
| **FY2025** (Dec 31, 2025) | $246,597M | $261,126M |
| **Q3 2025** (Sep 30, 2025) | $223,787M | — |
| **FY2024** (Dec 31, 2024) | $171,036M | — |
| **FY2023** (Dec 31, 2023) | $134,345M | $112,308M |
| **FY2022** (Dec 31, 2022) | $112,668M | $82,755M |

### Key Observation:
- Both Google and Microsoft have reached **~$280B+ in net PP&E** as of Q1 2026
- Google grew net PP&E by **~$110B (~63%)** from Dec 2023 to Mar 2026
- Microsoft grew from ~$112B (Dec 2022) to ~$283B (Mar 2026) — roughly **+152% in ~3.5 years**

---

## 2. Amazon: Depreciation & Amortization as an Infrastructure Proxy

Amazon's D&A reflects the consumption of previously invested infrastructure (cumulative YTD):

| Period | Annual D&A |
|--------|-----------|
| **FY2025** (Dec 31, 2025) | **$65,756M** |
| **FY2024** (Dec 31, 2024) | $52,795M |
| **FY2023** (Dec 31, 2023) | $48,663M |
| **FY2022** (Dec 31, 2022) | $41,921M |
| Q1 2026 (Mar 31, 2026) | $18,945M (quarterly run rate ~$75.8B annualized) |

Amazon's **rising D&A** signals massive prior capital investment now being depreciated, consistent with heavy data center buildout.

---

## 3. Growth Trajectory Summary

| Company | Metric Used | ~2022 Value | ~Q1 2026 Value | % Growth |
|---------|------------|-------------|----------------|----------|
| **Google** | Net PP&E | $112.7B | $281.0B | **+149%** |
| **Microsoft** | Net PP&E | $82.8B | $283.2B | **+242%** |
| **Amazon** | Annual D&A | $41.9B | ~$75.8B (annualized) | **+81%** |

---

## Key Takeaways

1. **Microsoft has shown the steepest growth** in infrastructure assets (net PP&E), surging from ~$83B (FY2022) to ~$283B (Q1 2026), largely driven by Azure and AI investments.

2. **Google is nearly neck-and-neck** with Microsoft at ~$281B net PP&E as of Q1 2026, up dramatically from $112.7B in FY2022.

3. **Amazon's infrastructure scale** cannot be directly compared via the same metric from this dataset, but its rapidly growing D&A (~$65.8B in FY2025) implies an enormous underlying asset base, consistent with AWS being the largest cloud provider.

4. **All three companies are accelerating spend**, consistent with AI-driven demand for data center capacity — as noted in Google's filings, investments include **"servers and network equipment for computing, storage and networking... including AI."**

> 📌 **Limitation:** Direct capex figures (purchases of property & equipment) were not included in the retrieved data for any of the three companies. For a more precise comparison, capital expenditure line items from cash flow statements would be needed.

## Interactive Query Interface

In [7]:
def ask(question):
    """Simple interface - just ask a question!"""
    result = query_edgar(question, synthesize=True)
    
    if 'answer' in result:
        print("\n" + "="*60)
        print("ANSWER")
        print("="*60)
        print(result['answer'])
        print()
    
    return result

Example usage:

ask("What is Microsoft's total stockholders equity trend over the last 2 years?")

ask("What does Meta say about AI infrastructure investments?")

In [8]:
ask("What is Microsoft's total stockholders equity trend over the last 2 years?")

============================================================
QUERY: What is Microsoft's total stockholders equity trend over the last 2 years?
============================================================

Query type: quantitative
Tickers: ['MSFT']
SQL keywords: ['Total stockholders equity', 'Retained earnings', 'Additional paid-in capital', 'Total equity']
Date range: 2024-01-01 to 2026-12-31

🔢 Searching financial facts...
   Found 18 financial facts

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
# Microsoft Total Stockholders' Equity Trend (Last 2 Years)

## Summary Table

| Date | Total Stockholders' Equity | Period-over-Period Change |
|------|---------------------------|--------------------------|
| 2024-03-31 | $253,152M | — |
| 2024-06-30 | $268,477M | +$15,325M (+6.1%) |
| 2024-09-30 | $287,723M | +$19,246M (+7.2%) |
| 2024-12-31 | $302,695M | +$14,972M (+5.2%) |
| 2025-03-31 | $321,891M | +$19,196M (+6.3%) |
| 2025-06-30 | $343,479M | +$21,588M (+6.7%) |
| 2025-09-30 | $363,076M | +$19,597M (+5.7%) |
| 2025-12-31 | $390,875M | +$27,799M (+7.7%) |
| 2026-03-31 | $414,367M | +$23,492M (+6.0%) |

---

## Key Findings

### 📈 Consistent and Strong Growth
Microsoft's total stockholders' equity has grown **steadily and without interruption** across every reported quarter.

### Overall Growth (2-Year Span)
- **From:** $253,152M (March 2024)
- **To:** $414,367M (March 2026)
- **Total Increase:** +$161,215M
- **Growth Rate:** ~**+63.7% over two years**

### Annual Milestones
- **FY2024 (ending June 2024):** $268,477M
- **FY2025 (ending June 2025):** $343,479M → +**$75,002M (+27.9% YoY)**

---

## Conclusion
Microsoft demonstrates a **robust and consistent upward trend** in stockholders' equity, driven largely by growing retained earnings (which rose from $159,394M in March 2024 to $302,526M in March 2026). This reflects strong and sustained profitability over the period.

{'financial_data':    ticker period_date statement_type                       label     value  \
 0    MSFT  2026-03-31  balance_sheet           Retained earnings  302526.0
 1    MSFT  2025-12-31  balance_sheet           Retained earnings  280789.0
 2    MSFT  2025-09-30  balance_sheet           Retained earnings  254873.0
 3    MSFT  2025-06-30  balance_sheet           Retained earnings  237731.0
 4    MSFT  2025-03-31  balance_sheet           Retained earnings  219759.0
 5    MSFT  2024-12-31  balance_sheet           Retained earnings  203482.0
 6    MSFT  2024-09-30  balance_sheet           Retained earnings  188929.0
 7    MSFT  2024-06-30  balance_sheet           Retained earnings  173144.0
 8    MSFT  2024-03-31  balance_sheet           Retained earnings  159394.0
 9    MSFT  2026-03-31  balance_sheet  Total stockholders’ equity  414367.0
 10   MSFT  2025-12-31  balance_sheet  Total stockholders’ equity  390875.0
 11   MSFT  2025-09-30  balance_sheet  Total stockholders’ equity  363076.0
 12   MSFT  2025-06-30  balance_sheet  Total stockholders’ equity  343479.0
 13   MSFT  2025-03-31  balance_sheet  Total stockholders’ equity  321891.0
 14   MSFT  2024-12-31  balance_sheet  Total stockholders’ equity  302695.0
 15   MSFT  2024-09-30  balance_sheet  Total stockholders’ equity  287723.0
 16   MSFT  2024-06-30  balance_sheet  Total stockholders’ equity  268477.0
 17   MSFT  2024-03-31  balance_sheet  Total stockholders’ equity  253152.0

         unit filing_type filing_date
 0   millions        10-Q  2026-04-29
 1   millions        10-Q  2026-01-28
 2   millions        10-Q  2025-10-29
 3   millions        10-K  2025-07-30
 4   millions        10-Q  2025-04-30
 5   millions        10-Q  2025-01-29
 6   millions        10-Q  2024-10-30
 7   millions        10-K  2025-07-30
 8   millions        10-Q  2024-04-25
 9   millions        10-Q  2026-04-29
 10  millions        10-Q  2026-01-28
 11  millions        10-Q  2025-10-29
 12  millions        10-K  2025-07-30
 13  millions        10-Q  2025-04-30
 14  millions        10-Q  2025-01-29
 15  millions        10-Q  2024-10-30
 16  millions        10-K  2025-07-30
 17  millions        10-Q  2024-04-25  ,
 'answer': "# Microsoft Total Stockholders' Equity Trend (Last 2 Years)\n\n## Summary Table\n\n| Date | Total Stockholders' Equity | Period-over-Period Change |\n|------|---------------------------|--------------------------|\n| 2024-03-31 | $253,152M | — |\n| 2024-06-30 | $268,477M | +$15,325M (+6.1%) |\n| 2024-09-30 | $287,723M | +$19,246M (+7.2%) |\n| 2024-12-31 | $302,695M | +$14,972M (+5.2%) |\n| 2025-03-31 | $321,891M | +$19,196M (+6.3%) |\n| 2025-06-30 | $343,479M | +$21,588M (+6.7%) |\n| 2025-09-30 | $363,076M | +$19,597M (+5.7%) |\n| 2025-12-31 | $390,875M | +$27,799M (+7.7%) |\n| 2026-03-31 | $414,367M | +$23,492M (+6.0%) |\n\n---\n\n## Key Findings\n\n### 📈 Consistent and Strong Growth\nMicrosoft's total stockholders' equity has grown **steadily and without interruption** across every reported quarter.\n\n### Overall Growth (2-Year Span)\n- **From:** $253,152M (March 2024)\n- **To:** $414,367M (March 2026)\n- **Total Increase:** +$161,215M\n- **Growth Rate:** ~**+63.7% over two years**\n\n### Annual Milestones\n- **FY2024 (ending June 2024):** $268,477M\n- **FY2025 (ending June 2025):** $343,479M → +**$75,002M (+27.9% YoY)**\n\n---\n\n## Conclusion\nMicrosoft demonstrates a **robust and consistent upward trend** in stockholders' equity, driven largely by growing retained earnings (which rose from $159,394M in March 2024 to $302,526M in March 2026). This reflects strong and sustained profitability over the period."}

In [9]:
ask("What does Meta say about AI infrastructure investments?")

============================================================
QUERY: What does Meta say about AI infrastructure investments?
============================================================

Query type: qualitative
Tickers: ['META']
SQL keywords: ['Technology and infrastructure', 'Capital expenditures', 'Property and equipment, net', 'Purchases of property and equipment', 'Depreciation and amortization']
Narrative query: Meta AI infrastructure investments capital expenditure data centers GPUs artificial intelligence spending strategy

📄 Searching narrative chunks...
   Found 5 relevant chunks

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
## Meta's AI Infrastructure Investments

Based on the SEC filing data provided, here is what Meta discloses about its AI infrastructure investments:

### Key Statements

**Significant and Growing Investment Commitment**
- Meta has **"significantly increased"** its infrastructure investments in connection with AI initiatives and **"expects investments to continue to increase"** (10-Q filed 2026-04-30)
- The company explicitly acknowledges that AI infrastructure spending is a major and expanding cost driver

**Driving Force Behind Compute Expansion**
- From the 2026 10-K: *"Our increased efforts toward building frontier AI models have driven a significant further expansion in our computing needs and we expect our computing needs to continue to expand as a result"*
- Meta has **designed and built its own data centers** and key portions of its technical infrastructure to support this

**Scope of AI Initiatives**
Infrastructure investments are tied to multiple goals:
- Recommending relevant content across products
- Enhancing advertising tools
- Developing **generative AI and superintelligence** capabilities
- Building new products and features

### Risk Acknowledgment
Meta explicitly warns that *"if our investments are not successful longer-term, our business and financial performance could be harmed"* — indicating these are **material, high-stakes commitments**.

> **Limitation:** The provided data does **not include specific dollar figures** for AI infrastructure spending. For precise capital expenditure numbers, Meta's income statements or capex disclosures would need to be referenced.

{'narrative_data':   ticker filing_type filing_date                           section  \
 0   META        10-K  2026-01-29                          Overview
 1   META        10-K  2025-01-30                          Overview
 2   META        10-K  2026-01-29                        Technology
 3   META        10-Q  2026-04-30  Risk Factors - Product Offerings
 4   META        10-Q  2023-07-27  Risk Factors - Product Offerings

                                           chunk_text  similarity
 0  We build technology that helps people connect ...    0.560472
 1  We build technology that helps people connect ...    0.545048
 2  #### Technology\nOur product development philo...    0.493610
 3  We may not be successful in our artificial int...    0.489166
 4  We may not be successful in our artificial int...    0.483952  ,
 'answer': '## Meta\'s AI Infrastructure Investments\n\nBased on the SEC filing data provided, here is what Meta discloses about its AI infrastructure investments:\n\n### Key Statements\n\n**Significant and Growing Investment Commitment**\n- Meta has **"significantly increased"** its infrastructure investments in connection with AI initiatives and **"expects investments to continue to increase"** (10-Q filed 2026-04-30)\n- The company explicitly acknowledges that AI infrastructure spending is a major and expanding cost driver\n\n**Driving Force Behind Compute Expansion**\n- From the 2026 10-K: *"Our increased efforts toward building frontier AI models have driven a significant further expansion in our computing needs and we expect our computing needs to continue to expand as a result"*\n- Meta has **designed and built its own data centers** and key portions of its technical infrastructure to support this\n\n**Scope of AI Initiatives**\nInfrastructure investments are tied to multiple goals:\n- Recommending relevant content across products\n- Enhancing advertising tools\n- Developing **generative AI and superintelligence** capabilities\n- Building new products and features\n\n### Risk Acknowledgment\nMeta explicitly warns that *"if our investments are not successful longer-term, our business and financial performance could be harmed"* — indicating these are **material, high-stakes commitments**.\n\n> **Limitation:** The provided data does **not include specific dollar figures** for AI infrastructure spending. For precise capital expenditure numbers, Meta\'s income statements or capex disclosures would need to be referenced.'}

### Simple Query Interface Examples from README

In [10]:
ask("How much did Amazon spend on infrastructure in 2025?")

============================================================
QUERY: How much did Amazon spend on infrastructure in 2025?
============================================================

Query type: quantitative
Tickers: ['AMZN']
SQL keywords: ['Capital expenditures', 'Purchases of property and equipment', 'Property and equipment, net', 'Technology and infrastructure', 'Infrastructure']
Date range: 2025-01-01 to 2025-12-31

🔢 Searching financial facts...
   Found 12 financial facts

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
## Amazon's Infrastructure Spending in 2025

Based on the SEC filing data, there are **two key metrics** that reflect Amazon's infrastructure investment in 2025:

---

### 1. Technology & Infrastructure (Operating Expenses)
From the **2025 10-K (full year ending December 31, 2025)**:
- **$108,521M (~$108.5 billion)** in Technology & Infrastructure expenses

### 2. Purchases of Property & Equipment (Capital Expenditures)
From the **2025 10-K (full year ending December 31, 2025)**:
- **$131,819M (~$131.8 billion)** in capital expenditures on property and equipment

---

### Context & Trend
The quarterly progression shows aggressive acceleration throughout 2025:

| Period | CapEx (Cumulative) | Tech & Infrastructure (Cumulative) |
|--------|-------------------|-------------------------------------|
| Q1 2025 | $25,019M | $22,994M |
| Q2 2025 | $57,202M | $50,160M |
| Q3 2025 | $92,297M | $79,122M |
| **Full Year 2025** | **$131,819M** | **$108,521M** |

---

### Summary
Depending on the definition used, Amazon spent approximately **$108.5 billion** on technology & infrastructure (operating) and **$131.8 billion** on property & equipment purchases (capital investment) in full-year 2025, reflecting significant infrastructure buildout, likely driven by AI and cloud (AWS) expansion.

{'financial_data':    ticker period_date    statement_type                                label  \
 0    AMZN  2025-12-31     balance_sheet          Property and equipment, net
 1    AMZN  2025-09-30     balance_sheet          Property and equipment, net
 2    AMZN  2025-06-30     balance_sheet          Property and equipment, net
 3    AMZN  2025-03-31     balance_sheet          Property and equipment, net
 4    AMZN  2025-12-31          cashflow  Purchases of property and equipment
 5    AMZN  2025-09-30          cashflow  Purchases of property and equipment
 6    AMZN  2025-06-30          cashflow  Purchases of property and equipment
 7    AMZN  2025-03-31          cashflow  Purchases of property and equipment
 8    AMZN  2025-12-31  income_statement        Technology and infrastructure
 9    AMZN  2025-09-30  income_statement        Technology and infrastructure
 10   AMZN  2025-06-30  income_statement        Technology and infrastructure
 11   AMZN  2025-03-31  income_statement        Technology and infrastructure

        value      unit filing_type filing_date
 0   357025.0  millions        10-K  2026-02-06
 1   324435.0  millions        10-Q  2025-10-31
 2   297616.0  millions        10-Q  2025-08-01
 3   272781.0  millions        10-Q  2025-05-02
 4   131819.0  millions        10-K  2026-02-06
 5    92297.0  millions        10-Q  2025-10-31
 6    57202.0  millions        10-Q  2025-08-01
 7    25019.0  millions        10-Q  2026-04-30
 8   108521.0  millions        10-K  2026-02-06
 9    79122.0  millions        10-Q  2025-10-31
 10   50160.0  millions        10-Q  2025-08-01
 11   22994.0  millions        10-Q  2026-04-30  ,
 'answer': "## Amazon's Infrastructure Spending in 2025\n\nBased on the SEC filing data, there are **two key metrics** that reflect Amazon's infrastructure investment in 2025:\n\n---\n\n### 1. Technology & Infrastructure (Operating Expenses)\nFrom the **2025 10-K (full year ending December 31, 2025)**:\n- **$108,521M (~$108.5 billion)** in Technology & Infrastructure expenses\n\n### 2. Purchases of Property & Equipment (Capital Expenditures)\nFrom the **2025 10-K (full year ending December 31, 2025)**:\n- **$131,819M (~$131.8 billion)** in capital expenditures on property and equipment\n\n---\n\n### Context & Trend\nThe quarterly progression shows aggressive acceleration throughout 2025:\n\n| Period | CapEx (Cumulative) | Tech & Infrastructure (Cumulative) |\n|--------|-------------------|-------------------------------------|\n| Q1 2025 | $25,019M | $22,994M |\n| Q2 2025 | $57,202M | $50,160M |\n| Q3 2025 | $92,297M | $79,122M |\n| **Full Year 2025** | **$131,819M** | **$108,521M** |\n\n---\n\n### Summary\nDepending on the definition used, Amazon spent approximately **$108.5 billion** on technology & infrastructure (operating) and **$131.8 billion** on property & equipment purchases (capital investment) in full-year 2025, reflecting significant infrastructure buildout, likely driven by AI and cloud (AWS) expansion."}

In [11]:
ask("What risks does Microsoft mention about AI and power?")

============================================================
QUERY: What risks does Microsoft mention about AI and power?
============================================================

Query type: qualitative
Tickers: ['MSFT']
SQL keywords: ['Research and development', 'Technology and infrastructure', 'Total operating expenses', 'General and administrative']
Narrative query: Microsoft AI artificial intelligence risks power energy consumption infrastructure

📄 Searching narrative chunks...
   Found 5 relevant chunks

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
## Microsoft's Disclosed Risks Around AI

Based on the SEC filings provided, Microsoft identifies the following key AI-related risks:

### Core AI Risks (mentioned across multiple filings, 2021–2023):

1. **Flawed Algorithms** – AI algorithms may be flawed, potentially undermining decisions, predictions, or analysis.
2. **Biased or Insufficient Datasets** – Datasets used to train AI may be insufficient or contain biased information.
3. **Inadequate Development/Deployment Practices** – Ineffective practices by Microsoft *or others* could result in harm (noted in the 10-Q filed **2022-10-25**).
4. **Reputational Harm or Liability** – Issues in AI development and use could expose Microsoft to competitive harm and legal liability.
5. **Controversial Data Practices** – Inappropriate or controversial data practices could "impair the acceptance of AI solutions" (10-Q filed **2021-01-26**).

### AI in IoT Context (10-Q 2022-10-25, 10-K 2022-07-28, 10-Q 2023-01-24):
- AI embedded in IoT solutions carries **security, privacy, and execution risks**, including device defects, limited ability to patch/update devices, and multi-layer vulnerabilities.

---

### ⚠️ Important Limitation:
The question asks specifically about **AI *and power*** risks. The provided data does **not contain any disclosures specifically linking AI to power consumption, energy usage, or electrical infrastructure risks**. If such disclosures exist in Microsoft's filings, they are not reflected in the retrieved data above.

{'narrative_data':   ticker filing_type filing_date                            section  \
 0   MSFT        10-Q  2022-10-25        Other digital safety abuses
 1   MSFT        10-Q  2021-01-26  Digital safety and service misuse
 2   MSFT        10-Q  2022-10-25        Other digital safety abuses
 3   MSFT        10-K  2022-07-28          Other digitalsafetyabuses
 4   MSFT        10-Q  2023-01-24          Other digitalsafetyabuses

                                           chunk_text  similarity
 0  Issues in the development and use of AI may re...    0.598362
 1  Issues in the use of AI in our offerings may r...    0.582525
 2  The development of the IoT presents security, ...    0.571642
 3  The development of the IoT presents security, ...    0.567342
 4  The development of the IoT presents security, ...    0.560389  ,
 'answer': '## Microsoft\'s Disclosed Risks Around AI\n\nBased on the SEC filings provided, Microsoft identifies the following key AI-related risks:\n\n### Core AI Risks (mentioned across multiple filings, 2021–2023):\n\n1. **Flawed Algorithms** – AI algorithms may be flawed, potentially undermining decisions, predictions, or analysis.\n2. **Biased or Insufficient Datasets** – Datasets used to train AI may be insufficient or contain biased information.\n3. **Inadequate Development/Deployment Practices** – Ineffective practices by Microsoft *or others* could result in harm (noted in the 10-Q filed **2022-10-25**).\n4. **Reputational Harm or Liability** – Issues in AI development and use could expose Microsoft to competitive harm and legal liability.\n5. **Controversial Data Practices** – Inappropriate or controversial data practices could "impair the acceptance of AI solutions" (10-Q filed **2021-01-26**).\n\n### AI in IoT Context (10-Q 2022-10-25, 10-K 2022-07-28, 10-Q 2023-01-24):\n- AI embedded in IoT solutions carries **security, privacy, and execution risks**, including device defects, limited ability to patch/update devices, and multi-layer vulnerabilities.\n\n---\n\n### ⚠️ Important Limitation:\nThe question asks specifically about **AI *and power*** risks. The provided data does **not contain any disclosures specifically linking AI to power consumption, energy usage, or electrical infrastructure risks**. If such disclosures exist in Microsoft\'s filings, they are not reflected in the retrieved data above.'}

In [12]:
ask("Compare data center spending across the hyperscalers")

============================================================
QUERY: Compare data center spending across the hyperscalers
============================================================

Query type: both
Tickers: ['AMZN', 'GOOGL', 'META', 'MSFT']
SQL keywords: ['Capital expenditures', 'Purchases of property and equipment', 'Property and equipment, net', 'Technology and infrastructure', 'Depreciation and amortization']
Narrative query: data center infrastructure capital expenditure spending investment hyperscaler cloud

🔢 Searching financial facts...
   Found 80 financial facts

📄 Searching narrative chunks...
   Found 5 relevant chunks

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
# Hyperscaler Data Center Spending Comparison

## Important Methodological Note

The retrieved data contains **different metrics** across companies, making a direct apples-to-apples comparison difficult. Here's what's available:

| Company | Metric Available | Most Recent Annual Figure |
|---------|-----------------|--------------------------|
| **AMZN** | Depreciation & Amortization (cash flow) | $65,756M (FY2025) |
| **GOOGL** | Property & Equipment, Net (balance sheet) | $246,597M (FY2025) |
| **META** | Depreciation & Amortization (cash flow) | $18,616M (FY2025) |
| **MSFT** | Property & Equipment, Net (balance sheet) | $261,126M (Dec 2025 quarter) |

---

## What We Can Compare

### Property & Equipment (Net Balance Sheet Values)
| Company | Dec 2022 | Dec 2023 | Dec 2024 | Latest |
|---------|----------|----------|----------|--------|
| **GOOGL** | $112,668M | $134,345M | $171,036M | $281,020M (Mar 2026) |
| **MSFT** | $82,755M | $112,308M | ~$230B+ | $283,228M (Mar 2026) |

- Both GOOGL and MSFT show **massive acceleration** in PP&E growth from 2023 onward, driven by AI/data center investment
- MSFT's PP&E roughly **tripled** from ~$82.8B (Dec 2022) to ~$283.2B (Mar 2026)
- GOOGL's PP&E roughly **2.5x** from ~$112.7B (Dec 2022) to ~$281.0B (Mar 2026)

### Depreciation & Amortization (Proxy for Accumulated Asset Base)
| Company | FY2022 | FY2023 | FY2024 | FY2025 | Q1 2026 |
|---------|--------|--------|--------|--------|---------|
| **AMZN** | $41,921M | $48,663M | $52,795M | $65,756M | $18,945M |
| **META** | $8,686M | $11,178M | $15,498M | $18,616M | $5,999M |

- **AMZN's D&A** is ~3.5x META's, reflecting Amazon's far larger infrastructure base (AWS + logistics)
- Both show consistent growth, with AMZN accelerating notably in FY2025 (+25% YoY)
- META's D&A grew +67% from FY2022 to FY2025, reflecting aggressive data center buildout

---

## Key Trends (All Companies)

1. **Acceleration post-2023**: All hyperscalers dramatically ramped infrastructure spending aligned with AI demand
2. **MSFT & GOOGL lead on absolute PP&E**: Both approaching ~$280B in net PP&E as of early 2026
3. **AMZN leads on D&A**: $65.8B in FY2025 D&A reflects the largest cumulative asset base among those with this metric
4. **META is the smallest** of the four on both metrics but growing fastest proportionally

---

## Limitation
The data does **not include capital expenditure (CapEx) figures** directly, which would be the most precise measure of *spending*. PP&E net balances reflect accumulated historical investment minus depreciation, and D&A reflects cost recovery on past spending — neither is a direct measure of current-period data center investment. Direct CapEx comparisons would require additional data not provided.

{'financial_data':    ticker period_date statement_type  \
 0    AMZN  2026-03-31       cashflow
 1    AMZN  2025-12-31       cashflow
 2    AMZN  2025-09-30       cashflow
 3    AMZN  2025-06-30       cashflow
 4    AMZN  2025-03-31       cashflow
 ..    ...         ...            ...
 75   MSFT  2023-03-31  balance_sheet
 76   MSFT  2022-06-30  balance_sheet
 77   MSFT  2023-09-30  balance_sheet
 78   MSFT  2023-12-31  balance_sheet
 79   MSFT  2024-03-31  balance_sheet

                                                 label     value      unit  \
 0   Depreciation and amortization of property and ...   18945.0  millions
 1   Depreciation and amortization of property and ...   65756.0  millions
 2   Depreciation and amortization of property and ...   46285.0  millions
 3   Depreciation and amortization of property and ...   29489.0  millions
 4   Depreciation and amortization of property and ...   14262.0  millions
 ..                                                ...       ...       ...
 75  Property and equipment, net of accumulated dep...   88132.0  millions
 76  Property and equipment, net of accumulated dep...   74398.0  millions
 77  Property and equipment, net of accumulated dep...  102502.0  millions
 78  Property and equipment, net of accumulated dep...  112308.0  millions
 79  Property and equipment, net of accumulated dep...  121375.0  millions

    filing_type filing_date
 0         10-Q  2026-04-30
 1         10-K  2026-02-06
 2         10-Q  2025-10-31
 3         10-Q  2025-08-01
 4         10-Q  2026-04-30
 ..         ...         ...
 75        10-Q  2023-04-25
 76        10-K  2023-07-27
 77        10-Q  2023-10-24
 78        10-Q  2024-01-30
 79        10-Q  2024-04-25

 [80 rows x 8 columns],
 'narrative_data':   ticker filing_type filing_date                          section  \
 0  GOOGL        10-Q  2022-10-26  Capital Expenditures and Leases
 1  GOOGL        10-Q  2022-04-27  Capital Expenditures and Leases
 2  GOOGL        10-Q  2022-07-27  Capital Expenditures and Leases
 3  GOOGL        10-K  2022-02-02  Capital Expenditures and Leases
 4  GOOGL        10-Q  2024-04-26  Capital Expenditures and Leases

                                           chunk_text  similarity
 0  #### Capital Expenditures and Leases\nWe make ...    0.533256
 1  #### Capital Expenditures and Leases\nWe make ...    0.533256
 2  #### Capital Expenditures and Leases\nWe make ...    0.533256
 3  #### Capital Expenditures and Leases\nWe make ...    0.523908
 4  #### Capital Expenditures and Leases\nWe make ...    0.514740  ,
 'answer': "# Hyperscaler Data Center Spending Comparison\n\n## Important Methodological Note\n\nThe retrieved data contains **different metrics** across companies, making a direct apples-to-apples comparison difficult. Here's what's available:\n\n| Company | Metric Available | Most Recent Annual Figure |\n|---------|-----------------|--------------------------|\n| **AMZN** | Depreciation & Amortization (cash flow) | $65,756M (FY2025) |\n| **GOOGL** | Property & Equipment, Net (balance sheet) | $246,597M (FY2025) |\n| **META** | Depreciation & Amortization (cash flow) | $18,616M (FY2025) |\n| **MSFT** | Property & Equipment, Net (balance sheet) | $261,126M (Dec 2025 quarter) |\n\n---\n\n## What We Can Compare\n\n### Property & Equipment (Net Balance Sheet Values)\n| Company | Dec 2022 | Dec 2023 | Dec 2024 | Latest |\n|---------|----------|----------|----------|--------|\n| **GOOGL** | $112,668M | $134,345M | $171,036M | $281,020M (Mar 2026) |\n| **MSFT** | $82,755M | $112,308M | ~$230B+ | $283,228M (Mar 2026) |\n\n- Both GOOGL and MSFT show **massive acceleration** in PP&E growth from 2023 onward, driven by AI/data center investment\n- MSFT's PP&E roughly **tripled** from ~$82.8B (Dec 2022) to ~$283.2B (Mar 2026)\n- GOOGL's PP&E roughly **2.5x** from ~$112.7B (Dec 2022) to ~$281.0B (Mar 2026)\n\n### Depreciation & Amortization (Proxy for Accumulated Asset Base)\n| Company | FY2022 | FY2023 | FY2024 | FY2025 | Q1 2026 |\n|---------|--------|--------|--------|--------|---------|\n| **AMZN** | $41,921M | $48,663M | $52,795M | $65,756M | $18,945M |\n| **META** | $8,686M | $11,178M | $15,498M | $18,616M | $5,999M |\n\n- **AMZN's D&A** is ~3.5x META's, reflecting Amazon's far larger infrastructure base (AWS + logistics)\n- Both show consistent growth, with AMZN accelerating notably in FY2025 (+25% YoY)\n- META's D&A grew +67% from FY2022 to FY2025, reflecting aggressive data center buildout\n\n---\n\n## Key Trends (All Companies)\n\n1. **Acceleration post-2023**: All hyperscalers dramatically ramped infrastructure spending aligned with AI demand\n2. **MSFT & GOOGL lead on absolute PP&E**: Both approaching ~$280B in net PP&E as of early 2026\n3. **AMZN leads on D&A**: $65.8B in FY2025 D&A reflects the largest cumulative asset base among those with this metric\n4. **META is the smallest** of the four on both metrics but growing fastest proportionally\n\n---\n\n## Limitation\nThe data does **not include capital expenditure (CapEx) figures** directly, which would be the most precise measure of *spending*. PP&E net balances reflect accumulated historical investment minus depreciation, and D&A reflects cost recovery on past spending — neither is a direct measure of current-period data center investment. Direct CapEx comparisons would require additional data not provided."}

### Quantitative Analysis examples from README

In [13]:
ask("What was Microsoft's total revenue in Q2 2025?")

============================================================
QUERY: What was Microsoft's total revenue in Q2 2025?
============================================================

Query type: quantitative
Tickers: ['MSFT']
SQL keywords: ['Revenue', 'Net revenue', 'Total revenue', 'Net sales']
Date range: 2024-10-01 to 2024-12-31

🔢 Searching financial facts...
   Found 5 financial facts

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
## Microsoft's Total Revenue in Q2 2025

Based on the SEC filing data provided, Microsoft's **total revenue was $135,217 million ($135.2 billion)** for the period ending **December 31, 2024** (as reported in their 10-Q filing).

> **Note on Timing:** Microsoft's fiscal year runs July–June, so the quarter ending December 31, 2024 represents **Microsoft's fiscal Q2 2025**, which aligns with the question asked.

### Key Context:
- **Total Revenue:** $135,217M
- **Cost of Revenue:** $41,898M
- **Implied Gross Profit:** ~$93,319M
- **Filing Type:** 10-Q (Quarterly Report)

> ⚠️ **Important Caveat:** The revenue figure of $135,217M appears to reflect a **year-to-date (6-month)** figure for the first half of fiscal year 2025 (July–December 2024), rather than a single quarter. The data provided does not isolate the standalone Q2 figure separately from Q1. For the precise single-quarter Q2 revenue, additional quarterly breakdown data would be needed.

{'financial_data':   ticker period_date    statement_type                        label     value  \
 0   MSFT  2024-12-31  income_statement              Cost of revenue   41898.0
 1   MSFT  2024-12-31     balance_sheet   Long-term unearned revenue    2537.0
 2   MSFT  2024-12-31  income_statement                      Revenue  135217.0
 3   MSFT  2024-12-31     balance_sheet  Short-term unearned revenue   45508.0
 4   MSFT  2024-12-31          cashflow             Unearned revenue  -11891.0

        unit filing_type filing_date
 0  millions        10-Q  2026-01-28
 1  millions        10-Q  2025-01-29
 2  millions        10-Q  2026-01-28
 3  millions        10-Q  2025-01-29
 4  millions        10-Q  2026-01-28  ,
 'answer': "## Microsoft's Total Revenue in Q2 2025\n\nBased on the SEC filing data provided, Microsoft's **total revenue was $135,217 million ($135.2 billion)** for the period ending **December 31, 2024** (as reported in their 10-Q filing).\n\n> **Note on Timing:** Microsoft's fiscal year runs July–June, so the quarter ending December 31, 2024 represents **Microsoft's fiscal Q2 2025**, which aligns with the question asked.\n\n### Key Context:\n- **Total Revenue:** $135,217M\n- **Cost of Revenue:** $41,898M\n- **Implied Gross Profit:** ~$93,319M\n- **Filing Type:** 10-Q (Quarterly Report)\n\n> ⚠️ **Important Caveat:** The revenue figure of $135,217M appears to reflect a **year-to-date (6-month)** figure for the first half of fiscal year 2025 (July–December 2024), rather than a single quarter. The data provided does not isolate the standalone Q2 figure separately from Q1. For the precise single-quarter Q2 revenue, additional quarterly breakdown data would be needed."}

In [14]:
ask("Compare operating expenses between Meta and Alphabet in 2024")

============================================================
QUERY: Compare operating expenses between Meta and Alphabet in 2024
============================================================

Query type: quantitative
Tickers: ['META', 'GOOGL']
SQL keywords: ['Total operating expenses', 'Research and development', 'General and administrative', 'Cost of revenue', 'Operating expenses']
Date range: 2024-01-01 to 2024-12-31

🔢 Searching financial facts...
   Found 24 financial facts

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
# Operating Expenses Comparison: Meta vs. Alphabet (2024 Full Year)

*Based on 10-K filings as of December 31, 2024*

---

## Side-by-Side Comparison

| Expense Category | Alphabet (GOOGL) | Meta | Difference |
|---|---|---|---|
| **Cost of Revenue** | $146,306M | $30,161M | Alphabet +$116,145M |
| **Research & Development** | $49,326M | $43,873M | Alphabet +$5,453M |
| **General & Administrative** | $14,188M | $9,740M | Alphabet +$4,448M |
| **Total (Sum of Above)** | **$209,820M** | **$83,774M** | **Alphabet +$126,046M** |

---

## Key Observations

1. **Overall Scale**: Alphabet's total operating expenses are approximately **2.5x larger** than Meta's, reflecting Alphabet's significantly larger revenue base.

2. **Cost of Revenue** is the starkest difference — Alphabet's is nearly **5x Meta's** ($146.3B vs. $30.2B), likely driven by Google's hardware, cloud infrastructure, and content acquisition costs.

3. **R&D is surprisingly close** — Meta's R&D spend ($43.9B) is only ~11% below Alphabet's ($49.3B), suggesting Meta is investing aggressively in AI and metaverse development relative to its size.

4. **G&A expenses** are more comparable, with Alphabet spending ~46% more than Meta ($14.2B vs. $9.7B).

---

> **Note:** The data provided reflects cumulative figures from annual 10-K filings. Sales & marketing expenses were **not included** in the retrieved data, so this comparison may not capture all operating expense line items.

{'financial_data':    ticker period_date    statement_type                       label     value  \
 0   GOOGL  2024-12-31  income_statement            Cost of revenues  146306.0
 1   GOOGL  2024-09-30  income_statement            Cost of revenues  105693.0
 2   GOOGL  2024-06-30  income_statement            Cost of revenues   69219.0
 3   GOOGL  2024-03-31  income_statement            Cost of revenues   33712.0
 4   GOOGL  2024-12-31  income_statement  General and administrative   14188.0
 5   GOOGL  2024-09-30  income_statement  General and administrative    9783.0
 6   GOOGL  2024-06-30  income_statement  General and administrative    6184.0
 7   GOOGL  2024-03-31  income_statement  General and administrative    3026.0
 8   GOOGL  2024-12-31  income_statement    Research and development   49326.0
 9   GOOGL  2024-09-30  income_statement    Research and development   36210.0
 10  GOOGL  2024-06-30  income_statement    Research and development   23763.0
 11  GOOGL  2024-03-31  income_statement    Research and development   11903.0
 12   META  2024-12-31  income_statement             Cost of revenue   30161.0
 13   META  2024-09-30  income_statement             Cost of revenue   21322.0
 14   META  2024-06-30  income_statement             Cost of revenue   13948.0
 15   META  2024-03-31  income_statement             Cost of revenue    6640.0
 16   META  2024-12-31  income_statement  General and administrative    9740.0
 17   META  2024-09-30  income_statement  General and administrative    8978.0
 18   META  2024-06-30  income_statement  General and administrative    7114.0
 19   META  2024-03-31  income_statement  General and administrative    3455.0
 20   META  2024-12-31  income_statement    Research and development   43873.0
 21   META  2024-09-30  income_statement    Research and development   31693.0
 22   META  2024-06-30  income_statement    Research and development   20515.0
 23   META  2024-03-31  income_statement    Research and development    9978.0

         unit filing_type filing_date
 0   millions        10-K  2026-02-05
 1   millions        10-Q  2025-10-30
 2   millions        10-Q  2025-07-24
 3   millions        10-Q  2025-04-25
 4   millions        10-K  2026-02-05
 5   millions        10-Q  2025-10-30
 6   millions        10-Q  2025-07-24
 7   millions        10-Q  2025-04-25
 8   millions        10-K  2026-02-05
 9   millions        10-Q  2025-10-30
 10  millions        10-Q  2025-07-24
 11  millions        10-Q  2025-04-25
 12  millions        10-K  2026-01-29
 13  millions        10-Q  2025-10-30
 14  millions        10-Q  2025-07-31
 15  millions        10-Q  2025-05-01
 16  millions        10-K  2026-01-29
 17  millions        10-Q  2025-10-30
 18  millions        10-Q  2025-07-31
 19  millions        10-Q  2025-05-01
 20  millions        10-K  2026-01-29
 21  millions        10-Q  2025-10-30
 22  millions        10-Q  2025-07-31
 23  millions        10-Q  2025-05-01  ,
 'answer': "# Operating Expenses Comparison: Meta vs. Alphabet (2024 Full Year)\n\n*Based on 10-K filings as of December 31, 2024*\n\n---\n\n## Side-by-Side Comparison\n\n| Expense Category | Alphabet (GOOGL) | Meta | Difference |\n|---|---|---|---|\n| **Cost of Revenue** | $146,306M | $30,161M | Alphabet +$116,145M |\n| **Research & Development** | $49,326M | $43,873M | Alphabet +$5,453M |\n| **General & Administrative** | $14,188M | $9,740M | Alphabet +$4,448M |\n| **Total (Sum of Above)** | **$209,820M** | **$83,774M** | **Alphabet +$126,046M** |\n\n---\n\n## Key Observations\n\n1. **Overall Scale**: Alphabet's total operating expenses are approximately **2.5x larger** than Meta's, reflecting Alphabet's significantly larger revenue base.\n\n2. **Cost of Revenue** is the starkest difference — Alphabet's is nearly **5x Meta's** ($146.3B vs. $30.2B), likely driven by Google's hardware, cloud infrastructure, and content acquisition costs.\n\n3. **R&D is surprisingly close** — Meta's R&D spend ($43.9B) is only ~11% below Alphabet's ($49.3B), suggesting Meta is investing aggressively in AI and metaverse development relative to its size.\n\n4. **G&A expenses** are more comparable, with Alphabet spending ~46% more than Meta ($14.2B vs. $9.7B).\n\n---\n\n> **Note:** The data provided reflects cumulative figures from annual 10-K filings. Sales & marketing expenses were **not included** in the retrieved data, so this comparison may not capture all operating expense line items."}

In [15]:
ask("Show me Amazon's cash flow trends over the past 8 quarters")

============================================================
QUERY: Show me Amazon's cash flow trends over the past 8 quarters
============================================================

Query type: quantitative
Tickers: ['AMZN']
SQL keywords: ['Net cash provided by operating activities', 'Free cash flow', 'Capital expenditures', 'Net cash used in investing activities', 'Cash and cash equivalents']
Date range: 2024-01-01 to 2026-06-17

🔢 Searching financial facts...
   Found 9 financial facts

🤖 Synthesizing answer with Claude...

============================================================
ANSWER
============================================================
# Amazon (AMZN) Cash & Cash Equivalents — 8-Quarter Trend

## Quarterly Data (Chronological Order)

| Quarter | Date | Cash & Equivalents | QoQ Change |
|---------|------|--------------------|------------|
| Q1 2024 | 2024-03-31 | $72,852M | — |
| Q2 2024 | 2024-06-30 | $71,178M | ▼ -$1,674M |
| Q3 2024 | 2024-09-30 | $75,091M | ▲ +$3,913M |
| Q4 2024 | 2024-12-31 | $78,779M | ▲ +$3,688M |
| Q1 2025 | 2025-03-31 | $66,207M | ▼ -$12,572M |
| Q2 2025 | 2025-06-30 | $57,741M | ▼ -$8,466M |
| Q3 2025 | 2025-09-30 | $66,922M | ▲ +$9,181M |
| Q4 2025 | 2025-12-31 | $86,810M | ▲ +$19,888M |
| Q1 2026 | 2026-03-31 | $101,816M | ▲ +$15,006M |

---

## Key Observations

- 📈 **Strong overall growth**: Cash grew from **$72.9B (Q1 2024)** to **$101.8B (Q1 2026)** — a **~40% increase** over the period
- 📉 **Notable dip in 2025**: Cash dropped sharply in **Q1–Q2 2025**, falling to a trough of **$57.7B**, likely reflecting heavy capital expenditure deployment
- 🚀 **Sharp recovery**: A significant rebound occurred in **H2 2025 through Q1 2026**, with cash surging by **~$44B** from the Q2 2025 low
- 💰 **Record level**: The most recent quarter (**Q1 2026**) shows an **all-time high of $101.8B**

> ⚠️ **Note:** This data reflects *cash and cash equivalents* balances only, not full operating/investing/financing cash flow statements. For a complete cash flow analysis, operating, investing, and financing activities from the cash flow statements would be needed.

{'financial_data':   ticker period_date statement_type                      label     value  \
 0   AMZN  2026-03-31  balance_sheet  Cash and cash equivalents  101816.0
 1   AMZN  2025-12-31  balance_sheet  Cash and cash equivalents   86810.0
 2   AMZN  2025-09-30  balance_sheet  Cash and cash equivalents   66922.0
 3   AMZN  2025-06-30  balance_sheet  Cash and cash equivalents   57741.0
 4   AMZN  2025-03-31  balance_sheet  Cash and cash equivalents   66207.0
 5   AMZN  2024-12-31  balance_sheet  Cash and cash equivalents   78779.0
 6   AMZN  2024-09-30  balance_sheet  Cash and cash equivalents   75091.0
 7   AMZN  2024-06-30  balance_sheet  Cash and cash equivalents   71178.0
 8   AMZN  2024-03-31  balance_sheet  Cash and cash equivalents   72852.0

        unit filing_type filing_date
 0  millions        10-Q  2026-04-30
 1  millions        10-K  2026-02-06
 2  millions        10-Q  2025-10-31
 3  millions        10-Q  2025-08-01
 4  millions        10-Q  2025-05-02
 5  millions        10-K  2026-02-06
 6  millions        10-Q  2024-11-01
 7  millions        10-Q  2024-08-02
 8  millions        10-Q  2024-05-01  ,
 'answer': '# Amazon (AMZN) Cash & Cash Equivalents — 8-Quarter Trend\n\n## Quarterly Data (Chronological Order)\n\n| Quarter | Date | Cash & Equivalents | QoQ Change |\n|---------|------|--------------------|------------|\n| Q1 2024 | 2024-03-31 | $72,852M | — |\n| Q2 2024 | 2024-06-30 | $71,178M | ▼ -$1,674M |\n| Q3 2024 | 2024-09-30 | $75,091M | ▲ +$3,913M |\n| Q4 2024 | 2024-12-31 | $78,779M | ▲ +$3,688M |\n| Q1 2025 | 2025-03-31 | $66,207M | ▼ -$12,572M |\n| Q2 2025 | 2025-06-30 | $57,741M | ▼ -$8,466M |\n| Q3 2025 | 2025-09-30 | $66,922M | ▲ +$9,181M |\n| Q4 2025 | 2025-12-31 | $86,810M | ▲ +$19,888M |\n| Q1 2026 | 2026-03-31 | $101,816M | ▲ +$15,006M |\n\n---\n\n## Key Observations\n\n- 📈 **Strong overall growth**: Cash grew from **$72.9B (Q1 2024)** to **$101.8B (Q1 2026)** — a **~40% increase** over the period\n- 📉 **Notable dip in 2025**: Cash dropped sharply in **Q1–Q2 2025**, falling to a trough of **$57.7B**, likely reflecting heavy capital expenditure deployment\n- 🚀 **Sharp recovery**: A significant rebound occurred in **H2 2025 through Q1 2026**, with cash surging by **~$44B** from the Q2 2025 low\n- 💰 **Record level**: The most recent quarter (**Q1 2026**) shows an **all-time high of $101.8B**\n\n> ⚠️ **Note:** This data reflects *cash and cash equivalents* balances only, not full operating/investing/financing cash flow statements. For a complete cash flow analysis, operating, investing, and financing activities from the cash flow statements would be needed.'}